### PR TITLE
Update ruby vips and carrierwave.

### PR DESCRIPTION
**Pull request by skunkworker**
This updates ruby-vips & carrierwave to the newer versions.
It also has fixes for setting the exif data more explicitly, to be inline with the newer ruby-vips api.

### CODE REVIEW

**Comment by eltiare** [comment]
Does the old API still work with the newer library?

**Comment by skunkworker** [comment]
Everything worked except for setting the exif data. `image.set('exif-Orientation', '')` but being more explicit about the type that was being set allowed it to work successfully. `image.set_type GObject::GSTR_TYPE, 'exif-Orientation', ''`

**Comment by skunkworker** [comment]
I will also update the `.travis.yml`

**Comment by eltiare** [comment]
I'd prefer to keep the dependencies' versions as low as possible for backwards compatibility. You never know when requiring an update in someone's project will break things. I'll play with this over the next week to find out what those minimum versions are, if you're not able to tackle that.

**Comment by raimondasv** [comment]
@eltiare any chances this could be released as a new gem version?

**Comment by eltiare** [comment]
@raimondasv My only concern is updating Carrierwave to the latest version. Does this need to happen? Has the API changed? I haven't been using Ruby as much as I used to, and haven't had the time to check on this stuff.

**Comment by eltiare** [comment]
I will merge the changes and release a new version. If someone freaks out about the carrierwave being too old then we'll change it. :)

**Comment by eltiare** [comment]
I've upgraded ruby-vips and pushed a new gem version.

**Comment by raimondasv** [comment]
@eltiare thank you!

**Pull request closed without merging**
